### ISSUE TITLE
Testing time

### ISSUE THREAD

**Issue by Dopervigest** [KonstantinUshenin/nndt#108]
When creating a new pull request CI-testing starts, and it consumes quite a bit of time, even though the project's tests are light. Most time (like 2/3) is spent on the step called 'Test requirements installation'. Can we do something about it? Like configure testing environment beforehand. This would speed up testing by three times.
If it isn't possible, just close this issue.
@maksim-dzhigil

**Comment by maksim-dzhigil** [comment]
I think, caching dependencies can help - https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows. I'll try to implement it.

**Comment by maksim-dzhigil** [comment]
There were a lot of problems, but I did it. This might help someone in the future - https://stackoverflow.com/questions/59127258/how-can-i-use-pip-cache-in-github-actions
