### ISSUE TITLE
Docs for math_core.py

### ISSUE THREAD

**Issue by KonstantinUshenin** [KonstantinUshenin/nndt#11]
math_core.py is a very straightforward collection of math functions and stochastic generators. It is pretty easy to describe documentation for all functions in this class.

**Comment by hanuel-89** [comment]
Hi @KonstantinUshenin 
Can I take up this issue?

**Comment by KonstantinUshenin** [comment]
Yep. Thank you very much, @hanuel-89 ! 
The file is here https://github.com/KonstantinUshenin/nndt/blob/main/nndt/math_core.py .
Make branch, add some docs using """ """, and make a pull request. 

`take_each_n` is an advanced 'range' iterator, it takes data according to the index and starts from the beginning of the array if the index is greater than the array length.
`grid_in_cube` is a sampling of points from a 3D cube according to a uniform grid.
`grid_in_cube2` is the same, but with other parameters.
`uniform_in_cube` is a uniform sampling of points from a 3d cube.

The basic tutorial about Python's docstrings: https://realpython.com/documenting-python-code/
This service helps you to check English: https://www.grammarly.com/
Do not hesitate to write any questions here, if something is difficult for you.
