### ISSUE TITLE
`nndt.init_collab()`

### ISSUE THREAD

**Issue by KonstantinUshenin** [KonstantinUshenin/nndt#120]
We should add method for initialization of Google Collab to work with pyvista.

**Comment by KonstantinUshenin** [comment]
@Dopervigest knows what to do here

**Comment by semyon-v-dot** [comment]
Where `init_collab` method should be placed? There: [vizualize.py](https://github.com/KonstantinUshenin/nndt/blob/main/nndt/vizualize.py)?
