### ISSUE TITLE
Geometry primitives

### ISSUE THREAD

**Issue by KonstantinUshenin** [KonstantinUshenin/nndt#5]
We need geometrical primitives in math_core.py. The code should provide implicit representation of shapes.

Examples:
 - https://github.com/ml-for-gp/jaxgptoolbox/blob/de15f5c27af44b6a11b1e087e602d57ce03c378d/general/sdf_circle.py
 - https://github.com/ml-for-gp/jaxgptoolbox/blob/de15f5c27af44b6a11b1e087e602d57ce03c378d/general/sdf_triangle.py

List of expected 3D objects:
 - Sphere
 - Box
 - Tetrahedron (equilateral)

List of expected 2D objects:
 - Circle
 - Square
 - Triangle (equilateral)

**Comment by KonstantinUshenin** [comment]
@hanuel-89 , could you look at this issue? I think it is an easy task for one more contribute.

**Comment by hanuel-89** [comment]
Sure. I'll look into it.

**Comment by KonstantinUshenin** [comment]
@hanuel-89 I want to tell more about the maintainer goals. We want to implement as much as possible methods from a computational anatomy using neural networks. Computational anatomy includes a lot of heterogeneous tasks. There are some examples: https://team.inria.fr/epione/en/research/computational-anatomy/ https://en.wikipedia.org/wiki/Computational_anatomy

We are forced to use JAX+HAIKU, because PyTorch and Tensorflow are really bad choices for [physically informed neural networks](https://en.wikipedia.org/wiki/Physics-informed_neural_networks) and [implicit representation](https://github.com/vsitzmann/awesome-implicit-representations).

3D objects may be presented for calculation as voxel model, surface mesh or point clouds. Implicit representation with neural network is advanced approach. The key concept for this code is [signed distance function](https://en.wikipedia.org/wiki/Signed_distance_function).

**Comment by KonstantinUshenin** [comment]
@hanuel-89 , I have just added `sdf_primitive_sphere` here https://github.com/KonstantinUshenin/nndt/blob/main/nndt/math_core.py 
It is the first primitive in this list.

**Comment by KonstantinUshenin** [comment]
Separate this to #128 #127 #126
